name: Nightly Test

# Run the nightly tests at at 8 AM UTC / 1 AM Pacific
on:
  schedule:
    - cron: "25 23 * * *"
jobs:
  docker:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - 
        uses: FranzDiebold/github-env-vars-action@v2
      - name: build local image and let it run
        run: make dev
        env:
          DEV_IMAGE: ${CI_REPOSITORY}:nightly
      
