name: Nightly Test

# Run the nightly tests at at 8 AM UTC / 1 AM Pacific
on:
  schedule:
    - cron: "0 8 * * *"
jobs:
  docker:
    runs-on: ubuntu-20.04
    env:
      PROD_IMAGE: rossbachp/${{ github.event.repository.name }}:nightly
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: build local image and let it run
        run: make dev
