ame: Nightly Test

# Run the nightly tests at at 8 AM UTC / 1 AM Pacific
on:
  schedule:
    - cron: "0 8 * * *"
jobs:
  docker:
    runs-on: ubuntu-20.04
    env:
      PROD_IMAGE: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:edge
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: build local image and let it run
        run: make dev
